DROP SCHEMA edumine_HRZZ CASCADE;

CREATE SCHEMA edumine_HRZZ;

CREATE TABLE edumine_HRZZ.SLIKA(
  id SERIAL PRIMARY KEY NOT NULL,
  opis CHAR(100),
  url CHAR(100)
  );
  
CREATE TABLE edumine_HRZZ.PREDLOZAK(
  id SERIAL PRIMARY KEY NOT NULL,
  tekst CHAR(5000) NOT NULL
);

CREATE TABLE edumine_HRZZ.TIP_ZADATKA(
  id SERIAL PRIMARY KEY NOT NULL,
  opis CHAR(100)
);

CREATE TABLE edumine_HRZZ.ZADATAK(
  id SERIAL PRIMARY KEY NOT NULL,
  tekst CHAR(5000) NOT NULL,
  predlozak_id INT NOT NULL REFERENCES edumine_HRZZ.PREDLOZAK(id),
  tip_zadatka_id INT REFERENCES edumine_HRZZ.TIP_ZADATKA(id)
);

CREATE TABLE edumine_HRZZ.PARAMETAR(
  id SERIAL PRIMARY KEY NOT NULL,
  naziv CHAR(30) NOT NULL,
  vrijednost DOUBLE PRECISION NOT NULL,
  zadatak_id INT NOT NULL REFERENCES edumine_HRZZ.ZADATAK(id)
);

CREATE TABLE edumine_HRZZ.RJESENJE(
  id SERIAL PRIMARY KEY NOT NULL,
  oznaka CHAR(10),
  tekst_vrijednost CHAR(100) NOT NULL,
  tekst_prikaz CHAR(100),
  tocnost BOOLEAN DEFAULT TRUE,
  zadatak_id INT NOT NULL REFERENCES edumine_HRZZ.ZADATAK(id)
);

CREATE TABLE edumine_HRZZ.TIP_ISPITA(
  id SERIAL PRIMARY KEY NOT NULL,
  opis CHAR(100)
);

CREATE TABLE edumine_HRZZ.ISPIT(
  id SERIAL PRIMARY KEY NOT NULL,
  datum DATE,
  opis CHAR(100),
  tip_ispita_id INT NOT NULL REFERENCES edumine_HRZZ.TIP_ISPITA(id)
);

CREATE TABLE edumine_HRZZ.ISPITNI_ZADATAK(
  id SERIAL PRIMARY KEY NOT NULL,
  zadatak_id INT NOT NULL REFERENCES edumine_HRZZ.ZADATAK(id),
  ispit_id INT NOT NULL REFERENCES edumine_HRZZ.ISPIT(id)
);

CREATE TABLE edumine_HRZZ.STUDENT(
  id SERIAL PRIMARY KEY NOT NULL,
  nick CHAR(10),
  email CHAR(50) NOT NULL,
  JMBAG CHAR(10),
  OIB CHAR(11),
  prezime_ime CHAR(50),
  CHECK (nick IS NOT NULL AND JMBAG IS NOT NULL)
);

CREATE TABLE edumine_HRZZ.ISPITNI_ZADATAK_RJESENJE(
  id SERIAL PRIMARY KEY NOT NULL,
  tekstVrijednost CHAR(100),
  ispitni_zadatak_id INT NOT NULL REFERENCES edumine_HRZZ.ISPITNI_ZADATAK(id),
  rjesenje_id INT REFERENCES edumine_HRZZ.RJESENJE(id),
  student_id INT NOT NULL REFERENCES edumine_HRZZ.STUDENT(id),
  datum DATE,
  vrijeme TIME,
  CHECK (tekstVrijednost IS NOT NULL OR rjesenje_id IS NOT NULL)
);

CREATE TABLE edumine_HRZZ.TIP_GRUPE(
  id SERIAL PRIMARY KEY NOT NULL,
  opis CHAR(100)
);

CREATE TABLE edumine_HRZZ.GRUPA(
  id SERIAL PRIMARY KEY NOT NULL,
  opis CHAR(50),
  tip_grupe_id INT REFERENCES edumine_HRZZ.TIP_GRUPE(id)
);

CREATE TABLE edumine_HRZZ.STUDENT_GRUPA(
  id SERIAL PRIMARY KEY NOT NULL,
  student_id INT NOT NULL REFERENCES edumine_HRZZ.GRUPA(id),
  grupa_id INT NOT NULL REFERENCES edumine_HRZZ.STUDENT(id)
);

CREATE TABLE edumine_HRZZ.NASTAVNIK(
  id SERIAL PRIMARY KEY NOT NULL,
  nick CHAR(10),
  email CHAR(50) NOT NULL,
  OIB CHAR(11),
  prezime_ime CHAR(50),
  CHECK (nick IS NOT NULL OR email IS NOT NULL)
);

CREATE TABLE edumine_HRZZ.KOMENTAR(
  id SERIAL PRIMARY KEY NOT NULL,
  email CHAR(50),
  tekst CHAR(1000) NOT NULL,
  predlozak_id INT REFERENCES edumine_HRZZ.PREDLOZAK(id),
  nastavnik_id INT REFERENCES edumine_HRZZ.NASTAVNIK(id)
);

CREATE TABLE edumine_HRZZ.TIP_MATERIJALA(
  id SERIAL PRIMARY KEY NOT NULL,
  opis CHAR(100) NOT NULL
);

CREATE TABLE edumine_HRZZ.NASTAVNI_MATERIJAL(
  id SERIAL PRIMARY KEY NOT NULL,
  opis CHAR(100) NOT NULL,
  URL CHAR(50),
  tip_materijala_id INT NOT NULL REFERENCES edumine_HRZZ.TIP_MATERIJALA(id)
);

CREATE TABLE edumine_HRZZ.IZVOR_PREDLOSKA(
  id SERIAL PRIMARY KEY NOT NULL,
  predlozak_id INT NOT NULL REFERENCES edumine_HRZZ.PREDLOZAK(id),
  materijal_id INT NOT NULL REFERENCES edumine_HRZZ.NASTAVNI_MATERIJAL(id)
);


CREATE TABLE edumine_HRZZ.TIP_VEZE_KONCEPTA(
  id SERIAL PRIMARY KEY NOT NULL,
  opis CHAR(100) NOT NULL
);

CREATE TABLE edumine_HRZZ.TIP_KONCEPTA(
  id SERIAL PRIMARY KEY NOT NULL,
  opis CHAR(100) NOT NULL
);

CREATE TABLE edumine_HRZZ.KONCEPT(
  id SERIAL PRIMARY KEY NOT NULL,
  opis CHAR(100) NOT NULL
);

CREATE TABLE edumine_HRZZ.VEZA_KONCEPATA(
  id SERIAL PRIMARY KEY NOT NULL,
  tip_veze_koncepta_id INT NOT NULL REFERENCES edumine_HRZZ.TIP_VEZE_KONCEPTA(id),
  izvor_koncept_id INT NOT NULL REFERENCES edumine_HRZZ.KONCEPT(id),
  odrediste_koncept_id INT NOT NULL REFERENCES edumine_HRZZ.KONCEPT(id)
);

CREATE TABLE edumine_HRZZ.MATERIJAL_KONCEPT(
  id SERIAL PRIMARY KEY NOT NULL,
  koncept_id INT NOT NULL REFERENCES edumine_HRZZ.KONCEPT(id),
  materijal_id INT NOT NULL REFERENCES edumine_HRZZ.NASTAVNI_MATERIJAL(id)
);

CREATE TABLE edumine_HRZZ.KONCEPT_TIP(
  id SERIAL PRIMARY KEY NOT NULL,
  koncept_id INT NOT NULL REFERENCES edumine_HRZZ.KONCEPT(id),
  tip_koncepta_id INT NOT NULL REFERENCES edumine_HRZZ.TIP_KONCEPTA(id)
);


CREATE TABLE edumine_HRZZ.KLJUCNA_RIJEC(
  id SERIAL PRIMARY KEY NOT NULL,
  opis CHAR(100) NOT NULL
);


CREATE TABLE edumine_HRZZ.KLJUCNA_RIJEC_KONCEPT(
  id SERIAL PRIMARY KEY NOT NULL,
  koncept_id INT NOT NULL REFERENCES edumine_HRZZ.KONCEPT(id),
  kljucna_rijec_id INT NOT NULL REFERENCES edumine_HRZZ.KLJUCNA_RIJEC(id)
);

CREATE TABLE edumine_HRZZ.KLJUCNA_RIJEC_PREDLOZAK(
  id SERIAL PRIMARY KEY NOT NULL,
  koncept_id INT NOT NULL REFERENCES edumine_HRZZ.KONCEPT(id),
  predlozak_id INT NOT NULL REFERENCES edumine_HRZZ.PREDLOZAK(id)
);

CREATE TABLE edumine_HRZZ.PREDLOZAK_KONCEPT(
  id SERIAL PRIMARY KEY NOT NULL,
  predlozak_id INT NOT NULL REFERENCES edumine_HRZZ.PREDLOZAK(id),
  koncept_id INT NOT NULL REFERENCES edumine_HRZZ.KONCEPT(id)
);

CREATE TABLE edumine_HRZZ.STUDENT_KONCEPT(
  id SERIAL PRIMARY KEY NOT NULL,
  student_id INT NOT NULL REFERENCES edumine_HRZZ.STUDENT(id),
  koncept_id INT NOT NULL REFERENCES edumine_HRZZ.KONCEPT(id)
);

